### ISSUE TITLE
not published to apm

### ISSUE THREAD

**Issue by magalhas** [benmills/atom-jenkins#1]
Any reason why?

**Comment by benmills** [comment]
No real reason. I don't really use Atom and I made this plugin as an
experiment to play around with Atom.

**Comment by magalhas** [comment]
Ok. Thank you for clarifying. Me and everyone in my company is using Atom and Jenkins and I would like to maintain and continue the development of this plugin.

Do you mind moving it or having me fork it and releasing it to `apm`?

**Comment by benmills** [comment]
If you're ok forking it I would prefer that since it's nice to have around in my archive. I have no issue if you publish it to apm under your name.

**Comment by magalhas** [comment]
I'll fork it then. Thank you :+1:
